name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World!"
      - name: Execution
        run: |
            echo "Checking git version installed"
            git --version
      - name: Print Goodbye
        run: echo "Done - Goodbye!"
